# Generated by Django 4.2.7 on 2023-12-16 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HallManagementApp', '0002_applicationform_batch_department_payment_session_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_number',
            new_name='registration_number',
        ),
    ]
