# Generated by Django 4.2.1 on 2024-01-21 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HallManagementApp', '0004_feeshead'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeshead',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HallManagementApp.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HallManagementApp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HallManagementApp.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HallManagementApp.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HallManagementApp.session'),
        ),
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feeshead', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HallManagementApp.feeshead')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HallManagementApp.student')),
            ],
        ),
    ]
