# Generated by Django 4.2.1 on 2024-01-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallManagementApp', '0005_feeshead_amount_alter_applicationform_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
