# Generated by Django 5.0.2 on 2024-05-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallManagementApp', '0009_remove_student_user_student_userprofile'),
        ('core', '0003_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='studentfees',
            name='entryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfees',
            name='entryuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile'),
        ),
        migrations.AddField(
            model_name='studentfees',
            name='paymentStatus',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='paid', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entryDate', models.DateTimeField()),
                ('transactionType', models.CharField(choices=[('bkash', 'Bkash'), ('rocket', 'Rocket'), ('nagad', 'Nagad')], max_length=20)),
                ('transactionId', models.CharField(max_length=100)),
                ('transactionDetails', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='HallManagementApp.student')),
                ('studentFee', models.ManyToManyField(related_name='transactions', to='HallManagementApp.studentfees')),
            ],
        ),
        migrations.AddField(
            model_name='studentfees',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='HallManagementApp.semester'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
