# Generated by Django 5.0.2 on 2024-05-14 12:30

import HallManagementApp.models
import django_enum_choices.choice_builders
import django_enum_choices.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HallManagementApp', '0010_semester_studentfees_entrydate_studentfees_entryuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfees',
            name='paymentStatus',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[("('P', 'Paid')", "('P', 'Paid')"), ("('U', 'Unpaid')", "('U', 'Unpaid')")], default=HallManagementApp.models.Payment_Status['UNPAID'], enum_class=HallManagementApp.models.Payment_Status, max_length=15),
        ),
    ]
