# Generated by Django 5.0.2 on 2024-05-27 20:45

import HallManagementApp.models
import django_enum_choices.choice_builders
import django_enum_choices.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HallManagementApp', '0011_alter_studentfees_paymentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('3-2', '3-2'), ('4-1', '4-1'), ('4-2', '4-2')], default=HallManagementApp.models.Semester_Status['Semester_1'], enum_class=HallManagementApp.models.Semester_Status, max_length=3),
        ),
        migrations.AlterField(
            model_name='feetransaction',
            name='transactionType',
            field=models.CharField(choices=[('cash', 'Cash'), ('bkash', 'Bkash'), ('rocket', 'Rocket'), ('nagad', 'Nagad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfees',
            name='paymentStatus',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('P', 'P'), ('U', 'U')], default=HallManagementApp.models.Payment_Status['UNPAID'], enum_class=HallManagementApp.models.Payment_Status, max_length=1),
        ),
    ]
