# Generated by Django 5.0.2 on 2024-06-04 17:29

import core.models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FeesHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.hall')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=20)),
                ('semester', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('3-2', '3-2'), ('4-1', '4-1'), ('4-2', '4-2')], default=core.models.Semester_Status['Semester_1'], enum_class=core.models.Semester_Status, max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.batch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.department')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.room')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.session')),
                ('userprofile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentStatus', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('P', 'P'), ('U', 'U')], default=core.models.Payment_Status['UNPAID'], enum_class=core.models.Payment_Status, max_length=1)),
                ('entryDate', models.DateTimeField(blank=True, null=True)),
                ('entryuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile')),
                ('feeshead', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.feeshead')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entryDate', models.DateTimeField()),
                ('transactionType', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'Bkash'), ('rocket', 'Rocket'), ('nagad', 'Nagad')], max_length=20)),
                ('transactionId', models.CharField(max_length=100)),
                ('transactionDetails', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.student')),
                ('studentFee', models.ManyToManyField(related_name='transactions', to='core.studentfees')),
            ],
        ),
    ]
