# Generated by Django 5.0.2 on 2024-06-04 19:51

import core.models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_batch_department_feeshead_hall_semester_session_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationform',
            name='student',
        ),
        migrations.AddField(
            model_name='applicationform',
            name='application_status',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default=core.models.Application_Status['Pending'], enum_class=core.models.Application_Status, max_length=8),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='entryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='fullName',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='guardian_address',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='guardian_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='idCardPicture',
            field=models.ImageField(default=1, upload_to='ApplicationImages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='picture',
            field=models.ImageField(default=1, upload_to='ApplicationImages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='preferred_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='registration_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationform',
            name='semester',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('3-2', '3-2'), ('4-1', '4-1'), ('4-2', '4-2')], default=core.models.Semester_Status['Semester_1'], enum_class=core.models.Semester_Status, max_length=3),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.DecimalField(decimal_places=0, default=4, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
