# Generated by Django 5.0.2 on 2024-06-04 20:05

import core.models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_applicationform_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DormitoryApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('1-1', '1-1'), ('1-2', '1-2'), ('2-1', '2-1'), ('2-2', '2-2'), ('3-1', '3-1'), ('3-2', '3-2'), ('4-1', '4-1'), ('4-2', '4-2')], default=core.models.Semester_Status['Semester_1'], enum_class=core.models.Semester_Status, max_length=3)),
                ('registration_number', models.CharField(max_length=20)),
                ('fullName', models.CharField(blank=True, max_length=400)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=20, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('picture', models.ImageField(upload_to='ApplicationImages')),
                ('idCardPicture', models.ImageField(upload_to='ApplicationImages')),
                ('guardian_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('guardian_address', models.CharField(blank=True, max_length=400)),
                ('application_status', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default=core.models.Application_Status['Pending'], enum_class=core.models.Application_Status, max_length=8)),
                ('application_date', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.batch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.department')),
                ('preferred_room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.room')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.session')),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicationForm',
        ),
    ]
