# Generated by Django 5.0.2 on 2024-06-21 15:32

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dormitoryapplications_delete_applicationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='birthDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='fullName',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='guardian_address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='guardian_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='preferred_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.room'),
        ),
    ]
