# Generated by Django 5.0.2 on 2024-06-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dormitoryapplications_application_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='idCardPicture',
            field=models.ImageField(blank=True, null=True, upload_to='ApplicationImages'),
        ),
    ]
