# Generated by Django 5.0.2 on 2024-06-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_dormitoryapplications_idcardpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitoryapplications',
            name='guardian_name',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dormitoryapplications',
            name='guardian_relation',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
