# Generated by Django 5.0.2 on 2024-06-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dormitoryapplications_guardian_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='application_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
