# Generated by Django 5.0.2 on 2024-08-08 20:27

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_dormitoryapplications_application_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='student',
            name='birthDate',
            field=models.DateField(default=datetime.datetime(2024, 8, 9, 2, 25, 47, 13019)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='da', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='fullName',
            field=models.CharField(default='full', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_address',
            field=models.CharField(default='fdas', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(default='adfs', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='32', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(default='fdsa', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='idCardPicture',
            field=models.ImageField(blank=True, null=True, upload_to='ApplicationImages'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='23423', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(default=234, upload_to='ApplicationImages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='application_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 2, 25, 47, 13019)),
        ),
    ]
