# Generated by Django 5.0.2 on 2024-08-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_student_name_remove_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='application_date',
            field=models.DateTimeField(),
        ),
    ]
