# Generated by Django 5.0.2 on 2024-08-09 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_dormitoryapplications_application_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitoryapplications',
            name='review_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
