# Generated by Django 5.0.2 on 2024-08-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_dormitoryapplications_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
