# Generated by Django 5.0.2 on 2024-08-09 20:00

import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_dormitoryapplications_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitoryapplications',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='dormitoryapplications',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
