# Generated by Django 5.1.3 on 2024-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_dormitoryapplications_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dormitoryapplications',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dormitoryapplications',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
