# Generated by Django 5.1.3 on 2024-12-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_dormitoryapplications_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
