# Generated by Django 5.2.2 on 2025-07-11 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_paidamount_feetransaction_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslcommerzsession',
            name='fee_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sslcommerz_session', to='core.feetransaction', verbose_name='fee transaction'),
        ),
    ]
