# Generated by Django 4.2.7 on 2024-02-12 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HallManagementApp', '0009_remove_student_user_student_userprofile'),
        ('Communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HallManagementApp.student')),
            ],
        ),
    ]
