# Generated by Django 4.2.7 on 2024-02-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('Communication', '0002_studentnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotice',
            name='userprofile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userprofile'),
        ),
    ]
