# Generated by Django 4.2.7 on 2024-02-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HallManagementApp', '0009_remove_student_user_student_userprofile'),
        ('Communication', '0003_studentnotice_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnotice',
            name='username',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentnotice',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HallManagementApp.student'),
        ),
    ]
