# Generated by Django 4.2.7 on 2023-12-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('batch', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('room_no', models.IntegerField()),
                ('about_student', models.TextField()),
            ],
        ),
    ]
