# Generated by Django 4.2.1 on 2024-01-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0003_rename_roll_number_student_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
